scrape_configs:
  #- job_name: blackbox_simplifate_gitlab
  #  scrape_interval: 10s
  #  metrics_path: /probe
  #  params:
  #    module: [http_2xx]
  #    target:
  #      - 'gitlab.simplifate.com'
  #  scheme: http
  #  static_configs:
  #  - targets:
  #    - 172.17.0.1:9115

  #- job_name: 'node-exporter-gitlab-simplifate'
  #  scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

  #  metrics_path: /node-exporter/metrics
  #  scheme: https
  #  static_configs:
  #    - targets: ['gitlab.simplifate.com']
  #      labels:  {'host': 'backup.simplifate.com'} 


  #- job_name: 'node-exporter-backup-simplifate'
  #  scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

  #  metrics_path: /node-exporter-backup/metrics
  #  scheme: https
  #  static_configs:
  #    - targets: ['gitlab.simplifate.com']

  - job_name: 'node' 
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['192.168.122.25:9100']
        labels:  {'host': 'docker.zlutazimnice.cz'} 
      #- targets: ['172.17.0.1:10100'] 
      #  labels:  {'host': 'crypto-alpha-backend'} 
      #- targets: ['172.17.0.1:10101'] 
      #  labels:  {'host': 'tm.alpha'} 
      #- targets: ['172.17.0.1:10102'] 
      #  labels:  {'host': 'matching.alpha'} 
      #- targets: ['172.17.0.1:10103'] 
      #  labels:  {'host': 'matching2.alpha'} 

  - job_name: 'cAdvisor' 
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    #static_configs:
     # - targets: ['172.17.0.1:10081'] 
     #   labels:  {'host': 'crypto-alpha-backend'} 
     # - targets: ['172.17.0.1:10082'] 
     #   labels:  {'host': 'tm.alpha'} 
     # - targets: ['172.17.0.1:10083'] 
     #   labels:  {'host': 'matching.alpha'} 
     # - targets: ['172.17.0.1:10083'] 
     #   labels:  {'host': 'matching2.alpha'} 



rule_files:
- '/etc/prometheus/*.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "172.17.0.1:9093"